Repository apigee/apigee-client-php, pull requests merged in 2021-04, with the labels that each got.

#132 restrict polyfill-mbstring to 1.20.0 / Fix travis-ci in feature-ngmint
  .travis.yml
  composer.json
  tests/Test/Entity/MockEntity.php
Labels: cla: yes

#131 Code for Purchase,Cancel,Listing of Purchased Products
  src/Api/ApigeeX/Controller/AcceptedRatePlanController.php
  src/Api/ApigeeX/Controller/AcceptedRatePlanControllerInterface.php
  src/Api/ApigeeX/Controller/DeveloperAcceptedRatePlanController.php
  src/Api/ApigeeX/Controller/ListingHelperTrait.php
  src/Api/ApigeeX/Controller/PaginatedListingHelperTrait.php
  src/Api/ApigeeX/Denormalizer/AcceptedRatePlanDenormalizer.php
  src/Api/ApigeeX/Denormalizer/DeveloperAcceptedRatePlanDenormalizer.php
  src/Api/ApigeeX/Entity/AcceptedRatePlan.php
  src/Api/ApigeeX/Entity/AcceptedRatePlanInterface.php
  src/Api/ApigeeX/Entity/DeveloperAcceptedRatePlan.php
  src/Api/ApigeeX/Entity/DeveloperAcceptedRatePlanInterface.php
  src/Api/ApigeeX/Entity/Property/ApiProductPropertyAwareTrait.php
  src/Api/ApigeeX/Entity/Property/ApiProductPropertyInterface.php
  src/Api/ApigeeX/Entity/Property/EndTimePropertyAwareTrait.php
  src/Api/ApigeeX/Entity/Property/EndTimePropertyInterface.php
  src/Api/ApigeeX/Entity/Property/StartTimePropertyAwareTrait.php
  src/Api/ApigeeX/Entity/Property/StartTimePropertyInterface.php
  src/Api/ApigeeX/Entity/RatePlanInterface.php
  src/Api/ApigeeX/Normalizer/AcceptedRatePlanNormalizer.php
  src/Api/ApigeeX/Serializer/AcceptedRatePlanSerializer.php
  src/Api/Monetization/Normalizer/EntityNormalizer.php
  src/Controller/AbstractEntityController.php
Labels: cla: yes, documentation, enhancement

#130 Initial Commit for NGMint (ApigeeX 5G)
  src/Api/ApigeeX/Controller/ApiProductController.php
  src/Api/ApigeeX/Controller/ApiProductControllerInterface.php
  src/Api/ApigeeX/Controller/RatePlanController.php
  src/Api/ApigeeX/Controller/RatePlanControllerInterface.php
  src/Api/ApigeeX/Denormalizer/ApiProductDenormalizer.php
  src/Api/ApigeeX/Denormalizer/RatePlanDenormalizer.php
  src/Api/ApigeeX/Denormalizer/RatePlanDenormalizerFactory.php
  src/Api/ApigeeX/Denormalizer/RatePlanRateDenormalizer.php
  src/Api/ApigeeX/Denormalizer/StandardRatePlanDenormalizer.php
  src/Api/ApigeeX/Entity/ApiProduct.php
  src/Api/ApigeeX/Entity/ApiProductInterface.php
  src/Api/ApigeeX/Entity/Property/BillingPeriodPropertyAwareTrait.php
  src/Api/ApigeeX/Entity/Property/BillingPeriodPropertyInterface.php
  src/Api/ApigeeX/Entity/Property/ConsumptionPricingTypePropertyAwareTrait.php
  src/Api/ApigeeX/Entity/Property/ConsumptionPricingTypePropertyInterface.php
  src/Api/ApigeeX/Entity/Property/CurrencyCodePropertyAwareTrait.php
  src/Api/ApigeeX/Entity/Property/CurrencyCodePropertyInterface.php
  src/Api/ApigeeX/Entity/Property/FixedFeeFrequencyPropertyAwareTrait.php
  src/Api/ApigeeX/Entity/Property/FixedFeeFrequencyPropertyInterface.php
  src/Api/ApigeeX/Entity/Property/NanosPropertyAwareTrait.php
  src/Api/ApigeeX/Entity/Property/NanosPropertyInterface.php
  src/Api/ApigeeX/Entity/Property/PaymentFundingModelPropertyAwareTrait.php
  src/Api/ApigeeX/Entity/Property/PaymentFundingModelPropertyInterface.php
  src/Api/ApigeeX/Entity/Property/RevenueShareTypePropertyAwareTrait.php
  src/Api/ApigeeX/Entity/Property/RevenueShareTypePropertyInterface.php
  src/Api/ApigeeX/Entity/Property/UnitsPropertyAwareTrait.php
  src/Api/ApigeeX/Entity/Property/UnitsPropertyInterface.php
  src/Api/ApigeeX/Entity/RatePlan.php
  src/Api/ApigeeX/Entity/RatePlanRevisionInterface.php
  src/Api/ApigeeX/Entity/StandardRatePlan.php
  src/Api/ApigeeX/Entity/StandardRatePlanInterface.php
  src/Api/ApigeeX/Entity/StandardRatePlanRevision.php
  src/Api/ApigeeX/NameConverter/RatePlanNameConverter.php
  src/Api/ApigeeX/Normalizer/ApiProductNormalizer.php
  src/Api/ApigeeX/Normalizer/RatePlanNormalizer.php
  src/Api/ApigeeX/Normalizer/RatePlanNormalizerFactory.php
  src/Api/ApigeeX/Normalizer/RatePlanRateNormalizer.php
  src/Api/ApigeeX/Normalizer/StandardRatePlanNormalizer.php
  src/Api/ApigeeX/Serializer/ApiProductSerializer.php
  src/Api/ApigeeX/Serializer/RatePlanSerializer.php
  src/Api/ApigeeX/Structure/ConsumptionPricingRate.php
  src/Api/ApigeeX/Structure/Fee.php
  src/Api/ApigeeX/Structure/FixedRecurringFee.php
  src/Api/ApigeeX/Structure/RatePlanXFee.php
  src/Api/ApigeeX/Structure/RevenueShareRates.php
  src/Controller/EntityListingControllerTrait.php
Labels: cla: yes, documentation, enhancement

#125 Closes-#108 - After creating app without description throwing php not…
  src/Denormalizer/AttributesPropertyDenormalizer.php
Labels: cla: yes

#133 App Analytics page - fix PHP error on empty data
  src/Api/Management/Controller/StatsController.php
Labels: cla: yes

#136 Feature ngmint - updated by pulling code from 2.x
  src/Api/Management/Controller/StatsController.php
  src/Denormalizer/AttributesPropertyDenormalizer.php
Labels: cla: yes, enhancement

#137 Bump version to 2.0.7 and changelog
  CHANGELOG.md
  src/ClientInterface.php
Labels: cla: yes

#139 ApiResponseException class throwing error on returning string response #138
  src/Exception/ApiResponseException.php
Labels: bug, cla: yes
