Repository apigee/apigee-client-php, pull requests merged in 2023-05, with the labels that each got.

#261 Http\Client\HttpClient deprecated used Psr\Http\Client\ClientInterface
  src/Client.php
  src/ClientInterface.php
Labels: bug

#260 Added channelID and channelURI for Appgroup.
  src/Api/ApigeeX/Entity/AppGroup.php
  src/Api/ApigeeX/Entity/AppGroupInterface.php
  src/Client.php
  src/ClientInterface.php
Labels: enhancement

#262 Changes for symfony 6.2 upgrade
  .github/workflows/php-test-workflow.yml
  composer.json
  psalm.xml.dist
  src/Api/ApigeeX/Entity/Property/StartTimePropertyAwareTrait.php
  src/Api/ApigeeX/Normalizer/ApiProductNormalizer.php
  src/Api/Management/Controller/AppCredentialController.php
  src/Api/Management/Entity/ApiProduct.php
  src/Api/Management/Normalizer/CompanyMembershipNormalizer.php
  src/Api/Monetization/Builder/RatePlanRevisionBuilder.php
  src/Api/Monetization/Entity/OrganizationProfile.php
  src/Api/Monetization/NameConverter/NameConverterBase.php
  src/Api/Monetization/Normalizer/ApiPackageNormalizer.php
  src/Api/Monetization/Normalizer/EntityNormalizer.php
  src/Api/Monetization/Normalizer/ReportCriteriaNormalizer.php
  src/Api/Monetization/Serializer/ReportDefinitionSerializer.php
  src/Controller/PaginationHelperTrait.php
  src/Denormalizer/EdgeDateDenormalizer.php
  src/Denormalizer/ObjectDenormalizer.php
  src/Exception/ApiException.php
  src/Exception/ApiRequestException.php
  src/Exception/ApiResponseException.php
  src/Exception/CpsNotEnabledException.php
  src/Exception/InvalidJsonException.php
  src/HttpClient/Plugin/Authentication/ApigeeOnGcpOauth2.php
  src/HttpClient/Plugin/Authentication/GceServiceAccount.php
  src/HttpClient/Plugin/Authentication/HybridOauth2.php
  src/HttpClient/Plugin/Authentication/Oauth.php
  src/HttpClient/Plugin/ResponseHandlerPlugin.php
  src/HttpClient/Utility/Builder.php
  src/HttpClient/Utility/BuilderInterface.php
  src/Normalizer/CredentialProductNormalizer.php
  src/Normalizer/ObjectNormalizer.php
  src/Normalizer/PropertiesPropertyNormalizer.php
  src/PropertyAccess/PropertyAccessorDecorator.php
  src/Serializer/EntitySerializer.php
  src/Serializer/JsonDecode.php
  src/Structure/KeyValueMapInterface.php
  tests/Api/Monetization/EntitySerializer/PropertyValidator/OrganizationProfileEntityReferencePropertyValidator.php
  tests/HttpClient/Utility/BuilderTest.php
  tests/Serializer/EntitySerializerTest.php
  tests/Structure/PropertiesPropertyTransformationTest.php
  tests/Test/HttpClient/DebuggerHttpClient.php
  tests/Test/HttpClient/FileSystemHttpMockClient.php
  tests/Test/HttpClient/FileSystemResponseFactory.php
  tests/Test/HttpClient/MockHttpClientInterface.php
  tests/Test/HttpClient/Plugin/MockApigeeOnGcpOauth2.php
  tests/Test/HttpClient/Plugin/MockHybridOauth2.php
  tests/Test/HttpClient/Plugin/MockOauth.php
  tests/Test/OnlineClientBase.php
Labels: Drupal 10 Preparation
